[package]
name = "rusoto_helper"
version = "0.1.0"
authors = ["Anthony DiMarco <ocramida@gmail.com>"]

[dependencies]
rusoto = { path = "../rusoto" }
rustc-serialize = "^0.3.16"
time = "^0.1.32"

[features]
aws_integration = ["dynamodb"]
dynamodb = []